// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coffee.shared.Models;

namespace coffee.api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200327204154_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("coffee.shared.Models.AuditingActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDatetime")
                        .HasColumnName("created_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ModifiedDateTime")
                        .HasColumnName("modified_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Result")
                        .HasColumnName("result")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnName("source")
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4")
                        .HasMaxLength(40);

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("auditing_actions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 27, 20, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 27, 20, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 27, 20, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 27, 20, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 27, 21, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 27, 21, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 27, 21, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 27, 21, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 27, 21, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 27, 21, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 27, 22, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 27, 22, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 7,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 27, 23, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 27, 23, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 27, 23, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 27, 23, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 0, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 0, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 1, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 1, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 11,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 2, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 2, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 12,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 3, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 3, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 4, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 4, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 14,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 5, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 5, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 15,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 6, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 6, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 16,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 8, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 8, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 17,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 9, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 9, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 18,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 10, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 10, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 19,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 28, 12, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 28, 12, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 29, 14, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 29, 14, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 21,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 29, 15, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 29, 15, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 22,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 29, 17, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 29, 17, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 23,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 29, 19, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 29, 19, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 24,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 29, 21, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 29, 21, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 25,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 29, 23, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 29, 23, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 26,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 30, 1, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 30, 1, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 27,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 30, 4, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 30, 4, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 28,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 30, 6, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 30, 6, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 29,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 30, 8, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 30, 8, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 30,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 30, 11, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 30, 11, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 31,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 30, 14, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 30, 14, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 32,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 30, 16, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 30, 16, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 33,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 30, 19, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 30, 19, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 34,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 30, 22, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 30, 22, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 35,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 31, 1, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 31, 1, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 36,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 31, 4, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 31, 4, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 37,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 31, 7, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 31, 7, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 38,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 31, 10, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 31, 10, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 39,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 1, 31, 13, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 1, 31, 13, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 40,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 1, 17, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 1, 17, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 41,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 1, 20, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 1, 20, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 42,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 1, 23, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 1, 23, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 43,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 2, 3, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 2, 3, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 44,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 2, 7, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 2, 7, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 45,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 2, 10, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 2, 10, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 46,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 2, 14, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 2, 14, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 47,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 2, 18, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 2, 18, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 48,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 2, 22, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 2, 22, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 49,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 3, 2, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 3, 2, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 50,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 3, 6, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 3, 6, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 51,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 3, 11, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 3, 11, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 52,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 3, 15, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 3, 15, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 53,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 3, 19, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 3, 19, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 54,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 4, 0, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 4, 0, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 55,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 4, 5, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 4, 5, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 56,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 4, 9, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 4, 9, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 57,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 4, 14, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 4, 14, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 58,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 4, 19, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 4, 19, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 59,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 5, 0, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 5, 0, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 60,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 6, 5, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 6, 5, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 61,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 6, 10, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 6, 10, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 62,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 6, 15, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 6, 15, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 63,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 6, 20, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 6, 20, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 64,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 7, 2, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 7, 2, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 65,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 7, 7, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 7, 7, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 66,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 7, 12, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 7, 12, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 67,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 7, 18, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 7, 18, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 68,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 8, 0, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 8, 0, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 69,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 8, 5, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 8, 5, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 70,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 8, 11, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 8, 11, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 71,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 8, 17, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 8, 17, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 72,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 8, 23, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 8, 23, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 73,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 9, 5, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 9, 5, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 74,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 9, 11, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 9, 11, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 75,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 9, 18, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 9, 18, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 76,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 10, 0, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 10, 0, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 77,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 10, 6, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 10, 6, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 78,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 10, 13, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 10, 13, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 79,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 10, 20, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 10, 20, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 80,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 12, 2, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 12, 2, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 81,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 12, 9, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 12, 9, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 82,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 12, 16, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 12, 16, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 83,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 12, 23, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 12, 23, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 84,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 13, 6, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 13, 6, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 85,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 13, 13, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 13, 13, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 86,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 13, 20, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 13, 20, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 87,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 14, 3, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 14, 3, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 88,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 14, 11, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 14, 11, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 89,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 14, 18, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 14, 18, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 90,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 15, 1, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 15, 1, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 91,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 15, 9, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 15, 9, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 92,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 15, 17, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 15, 17, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 93,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 16, 0, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 16, 0, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 94,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 16, 8, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 16, 8, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 95,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 16, 16, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 16, 16, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 96,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 17, 0, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 17, 0, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 97,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 17, 8, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 17, 8, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 98,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 17, 16, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 17, 16, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 99,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 18, 1, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 18, 1, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 100,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 19, 9, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 19, 9, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 101,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 19, 17, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 19, 17, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 102,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 20, 2, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 20, 2, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 103,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 20, 11, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 20, 11, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 104,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 20, 19, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 20, 19, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 105,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 21, 4, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 21, 4, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 106,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 21, 13, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 21, 13, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 107,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 21, 22, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 21, 22, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 108,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 22, 7, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 22, 7, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 109,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 22, 16, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 22, 16, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 110,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 23, 1, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 23, 1, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 111,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 23, 10, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 23, 10, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 112,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 23, 20, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 23, 20, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 113,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 24, 5, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 24, 5, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 114,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 24, 14, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 24, 14, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 115,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 25, 0, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 25, 0, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 116,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 25, 10, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 25, 10, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 117,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 25, 19, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 25, 19, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 118,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 26, 5, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 26, 5, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 119,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 26, 15, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 26, 15, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 120,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 28, 1, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 28, 1, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 121,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 28, 11, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 28, 11, 46, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 122,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 28, 21, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 28, 21, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 123,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 29, 8, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 29, 8, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 124,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 2, 29, 18, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 2, 29, 18, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 125,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 1, 4, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 1, 4, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 126,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 1, 15, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 1, 15, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 127,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 2, 2, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 2, 2, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 128,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 2, 12, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 2, 12, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 129,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 2, 23, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 2, 23, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 130,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 3, 10, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 3, 10, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 131,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 3, 21, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 3, 21, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 132,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 4, 8, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 4, 8, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 133,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 4, 19, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 4, 19, 16, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 134,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 5, 6, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 5, 6, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 135,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 5, 17, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 5, 17, 41, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 136,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 6, 5, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 6, 5, 1, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 137,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 6, 16, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 6, 16, 26, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 138,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 7, 3, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 7, 3, 56, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 139,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 7, 15, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 7, 15, 31, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        },
                        new
                        {
                            Id = 140,
                            CreatedDatetime = new DateTimeOffset(new DateTime(2020, 3, 9, 3, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedDateTime = new DateTimeOffset(new DateTime(2020, 3, 9, 3, 11, 53, 676, DateTimeKind.Unspecified).AddTicks(6027), new TimeSpan(0, 0, 0, 0, 0)),
                            Result = 3,
                            Source = ":8080",
                            Type = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
